from tests.fixtures import (
    wt_haplotype_array,
    mut_haplotype_array,
    bad_mutation_dataframe,
    good_mutation_dataframe,
    genotype_array,
    genotype_array_nans,
    genotype_similarity,
    spectra_array,
    callable_kmer_arr_mut,
    callable_kmer_arr_wt,
    haplotype_groups_ident,
    haplotype_groups_strat,
    one_covariate_matrix,
    multi_covariate_matrix,
)
